# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_deletestaffdialog.ui'
#
# Created: Mon Apr  2 16:27:25 2012
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DeleteStaffDialog(object):
    def setupUi(self, DeleteStaffDialog):
        DeleteStaffDialog.setObjectName(_fromUtf8("DeleteStaffDialog"))
        DeleteStaffDialog.resize(307, 338)
        self.verticalLayout = QtGui.QVBoxLayout(DeleteStaffDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(DeleteStaffDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.IdSpinBox = QtGui.QSpinBox(DeleteStaffDialog)
        self.IdSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.IdSpinBox.setMaximum(399)
        self.IdSpinBox.setObjectName(_fromUtf8("IdSpinBox"))
        self.horizontalLayout.addWidget(self.IdSpinBox)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(DeleteStaffDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(DeleteStaffDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.nameLabel = QtGui.QLabel(DeleteStaffDialog)
        self.nameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
        self.gridLayout.addWidget(self.nameLabel, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(DeleteStaffDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.genderLabel = QtGui.QLabel(DeleteStaffDialog)
        self.genderLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.genderLabel.setObjectName(_fromUtf8("genderLabel"))
        self.gridLayout.addWidget(self.genderLabel, 2, 2, 1, 1)
        self.messageLabel = QtGui.QLabel(DeleteStaffDialog)
        self.messageLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.messageLabel.setObjectName(_fromUtf8("messageLabel"))
        self.gridLayout.addWidget(self.messageLabel, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(DeleteStaffDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(DeleteStaffDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(DeleteStaffDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.wTimeLabel = QtGui.QLabel(DeleteStaffDialog)
        self.wTimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wTimeLabel.setObjectName(_fromUtf8("wTimeLabel"))
        self.gridLayout_2.addWidget(self.wTimeLabel, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(DeleteStaffDialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.wTypeLabel = QtGui.QLabel(DeleteStaffDialog)
        self.wTypeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wTypeLabel.setObjectName(_fromUtf8("wTypeLabel"))
        self.gridLayout_2.addWidget(self.wTypeLabel, 2, 2, 1, 1)
        self.workTypeLabel = QtGui.QLabel(DeleteStaffDialog)
        self.workTypeLabel.setObjectName(_fromUtf8("workTypeLabel"))
        self.gridLayout_2.addWidget(self.workTypeLabel, 3, 0, 1, 1)
        self.wPosLabel = QtGui.QLabel(DeleteStaffDialog)
        self.wPosLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.wPosLabel.setObjectName(_fromUtf8("wPosLabel"))
        self.gridLayout_2.addWidget(self.wPosLabel, 3, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.buttonBox = QtGui.QDialogButtonBox(DeleteStaffDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(3, 3)

        self.retranslateUi(DeleteStaffDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DeleteStaffDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DeleteStaffDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DeleteStaffDialog)

    def retranslateUi(self, DeleteStaffDialog):
        DeleteStaffDialog.setWindowTitle(QtGui.QApplication.translate("DeleteStaffDialog", "删除员工", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DeleteStaffDialog", "员工工号:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DeleteStaffDialog", "员工基本信息", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DeleteStaffDialog", "姓名:", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLabel.setText(QtGui.QApplication.translate("DeleteStaffDialog", "无", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("DeleteStaffDialog", "性别:", None, QtGui.QApplication.UnicodeUTF8))
        self.genderLabel.setText(QtGui.QApplication.translate("DeleteStaffDialog", "无", None, QtGui.QApplication.UnicodeUTF8))
        self.messageLabel.setText(QtGui.QApplication.translate("DeleteStaffDialog", "消息提示", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DeleteStaffDialog", "员工工作状态", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DeleteStaffDialog", "工作次数:", None, QtGui.QApplication.UnicodeUTF8))
        self.wTimeLabel.setText(QtGui.QApplication.translate("DeleteStaffDialog", "无", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DeleteStaffDialog", "工作类型:", None, QtGui.QApplication.UnicodeUTF8))
        self.wTypeLabel.setText(QtGui.QApplication.translate("DeleteStaffDialog", "无", None, QtGui.QApplication.UnicodeUTF8))
        self.workTypeLabel.setText(QtGui.QApplication.translate("DeleteStaffDialog", "当前位置:", None, QtGui.QApplication.UnicodeUTF8))
        self.wPosLabel.setText(QtGui.QApplication.translate("DeleteStaffDialog", "无", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DeleteStaffDialog = QtGui.QDialog()
    ui = Ui_DeleteStaffDialog()
    ui.setupUi(DeleteStaffDialog)
    DeleteStaffDialog.show()
    sys.exit(app.exec_())

