# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_updatestuffdialog.ui'
#
# Created: Mon Mar  5 08:45:08 2012
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_UpdateStuffDialog(object):
    def setupUi(self, UpdateStuffDialog):
        UpdateStuffDialog.setObjectName(_fromUtf8("UpdateStuffDialog"))
        UpdateStuffDialog.resize(387, 375)
        self.horizontalLayout = QtGui.QHBoxLayout(UpdateStuffDialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(UpdateStuffDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label = QtGui.QLabel(UpdateStuffDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.IdSpinBox = QtGui.QSpinBox(UpdateStuffDialog)
        self.IdSpinBox.setMinimum(1)
        self.IdSpinBox.setMaximum(300)
        self.IdSpinBox.setProperty(_fromUtf8("value"), 1)
        self.IdSpinBox.setObjectName(_fromUtf8("IdSpinBox"))
        self.gridLayout.addWidget(self.IdSpinBox, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(UpdateStuffDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.nameLineEdit = QtGui.QLineEdit(UpdateStuffDialog)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.gridLayout.addWidget(self.nameLineEdit, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(UpdateStuffDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.genderComboBox = QtGui.QComboBox(UpdateStuffDialog)
        self.genderComboBox.setObjectName(_fromUtf8("genderComboBox"))
        self.genderComboBox.addItem(_fromUtf8(""))
        self.genderComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.genderComboBox, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(UpdateStuffDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_2 = QtGui.QFrame(UpdateStuffDialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(UpdateStuffDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(UpdateStuffDialog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.wTimeSpinBox = QtGui.QSpinBox(UpdateStuffDialog)
        self.wTimeSpinBox.setEnabled(False)
        self.wTimeSpinBox.setObjectName(_fromUtf8("wTimeSpinBox"))
        self.gridLayout_2.addWidget(self.wTimeSpinBox, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(UpdateStuffDialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.wTypeComboBox = QtGui.QComboBox(UpdateStuffDialog)
        self.wTypeComboBox.setEnabled(False)
        self.wTypeComboBox.setObjectName(_fromUtf8("wTypeComboBox"))
        self.wTypeComboBox.addItem(_fromUtf8(""))
        self.wTypeComboBox.addItem(_fromUtf8(""))
        self.wTypeComboBox.addItem(_fromUtf8(""))
        self.wTypeComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.wTypeComboBox, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(UpdateStuffDialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.waitPosSpinBox = QtGui.QSpinBox(UpdateStuffDialog)
        self.waitPosSpinBox.setEnabled(False)
        self.waitPosSpinBox.setObjectName(_fromUtf8("waitPosSpinBox"))
        self.gridLayout_2.addWidget(self.waitPosSpinBox, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(UpdateStuffDialog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.workPosSpinBox = QtGui.QSpinBox(UpdateStuffDialog)
        self.workPosSpinBox.setEnabled(False)
        self.workPosSpinBox.setObjectName(_fromUtf8("workPosSpinBox"))
        self.gridLayout_2.addWidget(self.workPosSpinBox, 4, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(UpdateStuffDialog)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.buttonBox = QtGui.QDialogButtonBox(UpdateStuffDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)
        spacerItem1 = QtGui.QSpacerItem(20, 158, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.label.setBuddy(self.IdSpinBox)
        self.label_3.setBuddy(self.nameLineEdit)
        self.label_2.setBuddy(self.genderComboBox)
        self.label_7.setBuddy(self.wTimeSpinBox)
        self.label_8.setBuddy(self.wTypeComboBox)
        self.label_9.setBuddy(self.waitPosSpinBox)
        self.label_10.setBuddy(self.workPosSpinBox)

        self.retranslateUi(UpdateStuffDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), UpdateStuffDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), UpdateStuffDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(UpdateStuffDialog)
        UpdateStuffDialog.setTabOrder(self.IdSpinBox, self.nameLineEdit)
        UpdateStuffDialog.setTabOrder(self.nameLineEdit, self.genderComboBox)
        UpdateStuffDialog.setTabOrder(self.genderComboBox, self.wTimeSpinBox)
        UpdateStuffDialog.setTabOrder(self.wTimeSpinBox, self.wTypeComboBox)
        UpdateStuffDialog.setTabOrder(self.wTypeComboBox, self.waitPosSpinBox)
        UpdateStuffDialog.setTabOrder(self.waitPosSpinBox, self.workPosSpinBox)
        UpdateStuffDialog.setTabOrder(self.workPosSpinBox, self.buttonBox)

    def retranslateUi(self, UpdateStuffDialog):
        UpdateStuffDialog.setWindowTitle(QtGui.QApplication.translate("UpdateStuffDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("UpdateStuffDialog", "员工基本信息", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("UpdateStuffDialog", "*工号(&I)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("UpdateStuffDialog", "姓名(&N)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("UpdateStuffDialog", "*性别(&G)", None, QtGui.QApplication.UnicodeUTF8))
        self.genderComboBox.setItemText(0, QtGui.QApplication.translate("UpdateStuffDialog", "男", None, QtGui.QApplication.UnicodeUTF8))
        self.genderComboBox.setItemText(1, QtGui.QApplication.translate("UpdateStuffDialog", "女", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("UpdateStuffDialog", "(*为必填项目)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("UpdateStuffDialog", "员工工作状态", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("UpdateStuffDialog", "工作次数(&T)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("UpdateStuffDialog", "当前工作类型(&Y)", None, QtGui.QApplication.UnicodeUTF8))
        self.wTypeComboBox.setItemText(0, QtGui.QApplication.translate("UpdateStuffDialog", "排钟", None, QtGui.QApplication.UnicodeUTF8))
        self.wTypeComboBox.setItemText(1, QtGui.QApplication.translate("UpdateStuffDialog", "点钟", None, QtGui.QApplication.UnicodeUTF8))
        self.wTypeComboBox.setItemText(2, QtGui.QApplication.translate("UpdateStuffDialog", "选钟", None, QtGui.QApplication.UnicodeUTF8))
        self.wTypeComboBox.setItemText(3, QtGui.QApplication.translate("UpdateStuffDialog", "等待", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("UpdateStuffDialog", "等待位置(&W)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("UpdateStuffDialog", "当前工作位置(&P)", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    UpdateStuffDialog = QtGui.QDialog()
    ui = Ui_UpdateStuffDialog()
    ui.setupUi(UpdateStuffDialog)
    UpdateStuffDialog.show()
    sys.exit(app.exec_())

