#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updatestuff.ui'
#
# Created: Sat Mar  3 23:01:32 2012
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_UpdateStuff(object):
    def setupUi(self, UpdateStuff):
        UpdateStuff.setObjectName(_fromUtf8("UpdateStuff"))
        UpdateStuff.resize(387, 375)
        self.horizontalLayout = QtGui.QHBoxLayout(UpdateStuff)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(UpdateStuff)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label = QtGui.QLabel(UpdateStuff)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.IdComboBox = QtGui.QSpinBox(UpdateStuff)
        self.IdComboBox.setMinimum(1)
        self.IdComboBox.setMaximum(300)
        self.IdComboBox.setProperty(_fromUtf8("value"), 1)
        self.IdComboBox.setObjectName(_fromUtf8("IdComboBox"))
        self.gridLayout.addWidget(self.IdComboBox, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(UpdateStuff)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.nameLineEdit = QtGui.QLineEdit(UpdateStuff)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.gridLayout.addWidget(self.nameLineEdit, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(UpdateStuff)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.genderComboBox = QtGui.QComboBox(UpdateStuff)
        self.genderComboBox.setObjectName(_fromUtf8("genderComboBox"))
        self.genderComboBox.addItem(_fromUtf8(""))
        self.genderComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.genderComboBox, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(UpdateStuff)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line_2 = QtGui.QFrame(UpdateStuff)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(UpdateStuff)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(UpdateStuff)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.wTimeSpinBox = QtGui.QSpinBox(UpdateStuff)
        self.wTimeSpinBox.setObjectName(_fromUtf8("wTimeSpinBox"))
        self.gridLayout_2.addWidget(self.wTimeSpinBox, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(UpdateStuff)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.wTypeComboBox = QtGui.QComboBox(UpdateStuff)
        self.wTypeComboBox.setObjectName(_fromUtf8("wTypeComboBox"))
        self.wTypeComboBox.addItem(_fromUtf8(""))
        self.wTypeComboBox.addItem(_fromUtf8(""))
        self.wTypeComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.wTypeComboBox, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(UpdateStuff)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.waitPosSpinBox = QtGui.QSpinBox(UpdateStuff)
        self.waitPosSpinBox.setObjectName(_fromUtf8("waitPosSpinBox"))
        self.gridLayout_2.addWidget(self.waitPosSpinBox, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(UpdateStuff)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.workPosSpinBox = QtGui.QSpinBox(UpdateStuff)
        self.workPosSpinBox.setObjectName(_fromUtf8("workPosSpinBox"))
        self.gridLayout_2.addWidget(self.workPosSpinBox, 4, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(UpdateStuff)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.addPushButton = QtGui.QPushButton(UpdateStuff)
        self.addPushButton.setObjectName(_fromUtf8("addPushButton"))
        self.verticalLayout_2.addWidget(self.addPushButton)
        self.updatePushButton = QtGui.QPushButton(UpdateStuff)
        self.updatePushButton.setObjectName(_fromUtf8("updatePushButton"))
        self.verticalLayout_2.addWidget(self.updatePushButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.cancelButton = QtGui.QPushButton(UpdateStuff)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.verticalLayout_2.addWidget(self.cancelButton)
        spacerItem2 = QtGui.QSpacerItem(20, 158, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(UpdateStuff)
        QtCore.QMetaObject.connectSlotsByName(UpdateStuff)

    def retranslateUi(self, UpdateStuff):
        UpdateStuff.setWindowTitle(QtGui.QApplication.translate("UpdateStuff", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("UpdateStuff", "员工基本信息", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("UpdateStuff", "*工号", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("UpdateStuff", "姓名", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("UpdateStuff", "*性别", None, QtGui.QApplication.UnicodeUTF8))
        self.genderComboBox.setItemText(0, QtGui.QApplication.translate("UpdateStuff", "男", None, QtGui.QApplication.UnicodeUTF8))
        self.genderComboBox.setItemText(1, QtGui.QApplication.translate("UpdateStuff", "女", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("UpdateStuff", "(*为必填项目)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("UpdateStuff", "员工工作状态", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("UpdateStuff", "工作次数", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("UpdateStuff", "当前工作类型", None, QtGui.QApplication.UnicodeUTF8))
        self.wTypeComboBox.setItemText(0, QtGui.QApplication.translate("UpdateStuff", "排钟", None, QtGui.QApplication.UnicodeUTF8))
        self.wTypeComboBox.setItemText(1, QtGui.QApplication.translate("UpdateStuff", "点钟", None, QtGui.QApplication.UnicodeUTF8))
        self.wTypeComboBox.setItemText(2, QtGui.QApplication.translate("UpdateStuff", "选钟", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("UpdateStuff", "等待位置", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("UpdateStuff", "当前工作位置", None, QtGui.QApplication.UnicodeUTF8))
        self.addPushButton.setText(QtGui.QApplication.translate("UpdateStuff", "添加员工", None, QtGui.QApplication.UnicodeUTF8))
        self.updatePushButton.setText(QtGui.QApplication.translate("UpdateStuff", "确认修改", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("UpdateStuff", "取消", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    UpdateStuff = QtGui.QDialog()
    ui = Ui_UpdateStuff()
    ui.setupUi(UpdateStuff)
    UpdateStuff.show()
    sys.exit(app.exec_())

